### ISSUE TITLE
How to use the Adroit environment?

### ISSUE THREAD

**Issue by watchernyu** [vikashplus/Adroit#3]
Hi! Thank you for presenting this very interesting benchmark. I would like to try test some DRL algorithms on this environment, however, I'm not sure exactly how to use it in my code? (I would like to use it in a similar way as DMControl or OpenAI gym) 

It would be really helpful if you could point me to a tutorial or documentation page on how to use this benchmark! Thank you so much for the help! Really appreciate it!

**Comment by vikashplus** [comment]
Please see here -- https://github.com/vikashplus/mj_envs

**Comment by watchernyu** [comment]
Thanks a lot for your help!
